version: '3.9'

services:
  web:
    build:
      context: .
      target: runtime
    command: >
      gunicorn 
      -k uvicorn.workers.UvicornWorker 
      app.main:app 
      --bind 0.0.0.0:8000 
      --workers 4
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    restart: unless-stopped
    networks:
      - backend

  celery:
    build:
      context: .
      target: runtime
    command: celery -A app.core.celery_app.celery worker --loglevel=info
    env_file:
      - .env.prod
    depends_on:
      - web
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
