version: '3.9'
services:
  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: securepassword
      POSTGRES_DB: fastapi_prod
    volumes:
      - prod_db_data:/var/lib/postgresql/data
    networks:
      - backend

  web:
    build:
      context: .
      target: runtime
    command: >
      gunicorn 
      -k uvicorn.workers.UvicornWorker 
      app.main:app 
      --bind 0.0.0.0:8000 
      --workers 4
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:

volumes:
  prod_db_data:
