version: '3.9'
services:
  web:
    build:
      context: .
      target: runtime
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
    networks:
      - backend

networks:
  backend:
